---
- name: Set IOC username
  set_fact:
    repo_epics_ioc_user: "{{ item.epics_ioc_user | default(epics_ioc_user_name) }}"

- name: Set IOC directory name
  set_fact:
    repo_clone_path: "{{ item.clone_path | default(epics_ioc_clone_path) }}"

- name: Set IOC boot directory name
  set_fact:
    repo_ioc_boot_dir: "{{ item.epics_ioc_boot_dir | default(epics_ioc_boot_dir) }}"

- name: Set IOC autosave base directory name
  set_fact:
    repo_ioc_autosave_base_dir: "{{ item.epics_ioc_autosave_base_dir | default(epics_ioc_autosave_base_dir) }}"

- name: Set IOC autosave directory name
  set_fact:
    repo_ioc_autosave_dir: "{{ repo_ioc_autosave_base_dir }}/softioc-{{ item.repo_name }}"

- name: Set IOC initial environment variables
  set_fact:
    repo_ioc_env_vars: "{{ repo_ioc_env_vars | default({}) |
        combine(
            item.epics_ioc_env
        | default({}))
    }}"

- name: Set IOC EPICS_CA_ADDR_LIST if requested
  set_fact:
    repo_ioc_env_vars: "{{ repo_ioc_env_vars |
        combine({
            'EPICS_CA_ADDR_LIST': item.epics_ioc_env_epics_ca_addr_list
        })
    }}"
  when: item.epics_ioc_env_epics_ca_addr_list is defined and
        (item.epics_ioc_env_epics_ca_addr_list)

- name: Set IOC EPICS_CA_AUTO_ADDR_LIST if requested
  set_fact:
    repo_ioc_env_vars: "{{ repo_ioc_env_vars |
        combine({
            'EPICS_CA_AUTO_ADDR_LIST': 'YES' if (item.epics_ioc_env_epics_ca_auto_addr_list | bool) else 'NO'
        })
    }}"
  when: item.epics_ioc_env_epics_ca_auto_addr_list is defined and
        (item.epics_ioc_env_epics_ca_auto_addr_list)

- name: Set IOC EPICS_CA_MAX_ARRAY_BYTES if requested
  set_fact:
    repo_ioc_env_vars: "{{ repo_ioc_env_vars |
        combine({
            'EPICS_CA_MAX_ARRAY_BYTES': item.epics_ioc_env_epics_ca_max_array_bytes
        })
    }}"
  when: item.epics_ioc_env_epics_ca_max_array_bytes is defined and
        (item.epics_ioc_env_epics_ca_max_array_bytes)

- name: Set IOC EPICS_IOC_LOG_PORT
  set_fact:
    repo_ioc_env_vars: "{{ repo_ioc_env_vars |
        combine({
            'EPICS_IOC_LOG_PORT': item.epics_ioc_env_epics_ioc_log_port | default(epics_ioc_env_epics_ioc_log_port)
        })
    }}"

- name: Set EPICS_IOC_LOG_INET if requested
  set_fact:
    repo_ioc_env_vars: "{{ repo_ioc_env_vars |
        combine({
            'EPICS_IOC_LOG_INET': item.epics_ioc_env_epics_ioc_log_inet
        })
    }}"
  when: item.epics_ioc_env_epics_ioc_log_inet is defined and
        (item.epics_ioc_env_epics_ioc_log_inet)

- name: Set IOC EPICS_CA_SEC_FILE if requested
  set_fact:
    repo_ioc_env_vars: "{{ repo_ioc_env_vars |
        combine({
            'EPICS_CA_SEC_FILE': item.epics_ioc_env_epics_ca_sec_file
        })
    }}"
  when: item.epics_ioc_env_epics_ca_sec_file is defined and
        (item.epics_ioc_env_epics_ca_sec_file)

- name: Set IOC AUTOSAVE_DIR if requested
  set_fact:
    repo_ioc_env_vars: "{{ repo_ioc_env_vars |
        combine({
            'AUTOSAVE_DIR': repo_ioc_autosave_dir
        })
    }}"
  when: item.epics_manage_autosave_dir | default(false) | bool

- name: Show IOC environment variables
  debug:
    msg: "IOC environment variables: {{ repo_ioc_env_vars }}"

- name: Set IOC coresize
  set_fact:
    repo_ioc_coresize: "{{ (item.epics_ioc_systemd_coresize is defined and item.epics_ioc_systemd_coresize) |
        ternary(item.epics_ioc_systemd_coresize, epics_ioc_systemd_coresize) }}"

- name: Set IOC procServ log file
  set_fact:
    repo_ioc_procserv_log_file: "/var/log/softioc-{{ item.repo_name }}/procServ.log"

- name: Set IOC enable console port
  set_fact:
    repo_ioc_enable_console_port: "{{ (item.epics_ioc_systemd_enable_console_port is defined and item.epics_ioc_systemd_enable_console_port) |
        ternary(item.epics_ioc_systemd_enable_console_port, epics_ioc_systemd_enable_console_port) }}"

- name: Set IOC console port
  set_fact:
    repo_ioc_console_port: "{{ (item.epics_ioc_systemd_console_port is defined and item.epics_ioc_systemd_console_port) |
        ternary(item.epics_ioc_systemd_console_port, epics_ioc_systemd_console_port) }}"

- name: Set IOC systemd procServ console port string
  set_fact:
    repo_ioc_systemd_procserv_console_port: "--port {{ repo_ioc_console_port }}"
  when: repo_ioc_enable_console_port | bool

- name: Set IOC systemd procServ console port string to default
  set_fact:
    repo_ioc_systemd_procserv_console_port: ""
  when: not repo_ioc_enable_console_port | bool

- name: Set IOC enable unix domain socket
  set_fact:
    repo_ioc_enable_unix_domain_socket: "{{ (item.epics_ioc_systemd_enable_unix_domain_socket is defined and item.epics_ioc_systemd_enable_unix_domain_socket) |
        ternary(item.epics_ioc_systemd_enable_unix_domain_socket, epics_ioc_systemd_enable_unix_domain_socket) }}"

- name: Set default IOC unix domain socket
  set_fact:
    repo_ioc_default_unix_domain_socket: "softioc-{{ item.repo_name }}/procServ.sock"

- name: Set IOC unix domain socket
  set_fact:
    repo_ioc_unix_domain_socket: "{{ (item.epics_ioc_systemd_unix_domain_socket is defined and item.epics_ioc_systemd_unix_domain_socket) |
        ternary(item.epics_ioc_systemd_unix_domain_socket, repo_ioc_default_unix_domain_socket) }}"

- name: Set IOC systemd procServ unix domain socket string
  set_fact:
    repo_ioc_systemd_procserv_unix_domain_socket: "--port unix:/run/{{ repo_ioc_unix_domain_socket }}"
  when: repo_ioc_enable_unix_domain_socket | bool

- name: Set IOC systemd procServ unix domain socket string to default
  set_fact:
    repo_ioc_systemd_procserv_unix_domain_socket: ""
  when: not repo_ioc_enable_unix_domain_socket | bool

- name: Set IOC ProcServ time format
  set_fact:
    repo_ioc_procserv_timefmt: "{{ (item.epics_ioc_systemd_procserv_timefmt is defined and item.epics_ioc_systemd_procserv_timefmt) |
        ternary(item.epics_ioc_systemd_procserv_timefmt, epics_ioc_systemd_procserv_timefmt) }}"

- name: Set IOC ProcServ start script
  set_fact:
    repo_ioc_procserv_start_script: "{{ (item.epics_ioc_systemd_procserv_start_script is defined and item.epics_ioc_systemd_procserv_start_script) |
        ternary(item.epics_ioc_systemd_procserv_start_script, epics_ioc_systemd_procserv_start_script) }}"

- name: Set IOC systemd unit notify
  set_fact:
    repo_ioc_systemd_notify: "{{ (item.epics_ioc_systemd_notify is defined and item.epics_ioc_systemd_notify) |
        ternary(item.epics_ioc_systemd_notify, epics_ioc_systemd_notify) }}"

- name: Check if IOC directory already exists
  stat:
    path: "{{ repo_clone_path }}"
  register: clone_path_stat
  when: (item.install_via_makefile is defined and
        item.install_via_makefile | bool) or
        (item.clone_only is defined and
         item.clone_only | bool)

- name: Ensure IOC directory exists
  file:
    path: "{{ repo_clone_path }}"
    state: directory
    recurse: true
    mode: 0755
  become: true
  become_user: "{{ ansible_ssh_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id) }}"
  when: not clone_path_stat.stat.exists and
        ((item.install_via_makefile is defined and
        item.install_via_makefile | bool) or
        (item.clone_only is defined and
         item.clone_only | bool))

# Try to preserve local modifications with git stash. This is mostly
# so we can modify configuration files and make the git task idempotent
- name: Try to save local modifications if requested
  command: git stash
  args:
    chdir: "{{ repo_clone_path }}/{{ item.repo_name }}"
  changed_when: false
  failed_when: false
  when: item.repo_stash is defined and
        item.repo_stash | bool
  register: repo_stash

# Ansible user variable, ansible_user, ansible_ssh_user, etc is a mess.
# Going to use th approach in https://github.com/geerlingguy/drupal-vm/issues/1302
# to fix that.
- name: "Ensure repository {{ item.repo_name }} is cloned"
  git:
    repo: "{{ item.org_url }}/{{ item.repo_name }}"
    dest: "{{ repo_clone_path }}/{{ item.repo_name }}"
    version: "{{ item.repo_version | default('master') }}"
    accept_hostkey: "{{ item.git_accept_hostkey | default(omit) }}"
    ssh_opts: "{{ item.git_ssh_opts | default(omit) }}"
    force: "{{ item.force_version | default(false) }}"
  register: git_result
  become: true
  become_user: "{{ ansible_ssh_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id) }}"
  when: (item.install_via_makefile is defined and
        item.install_via_makefile | bool) or
        (item.clone_only is defined and
         item.clone_only | bool)

# Try to apply local modifications with git stash. This is mostly
# so we can modify configuration files and make the git task idempotent
- name: Try to apply local modifications if requested
  command: git stash pop
  args:
    chdir: "{{ repo_clone_path }}/{{ item.repo_name }}"
  changed_when: false
  failed_when: false
  when: item.repo_stash is defined and
        item.repo_stash | bool

- name: "Define {{ item.repo_name }} chdir variable"
  set_fact:
    repo_install_chdir: "{{ item.install_chdir | default('') }}"

- name: "Replace RELEASE file with a custom one for {{ item.repo_name }}"
  template:
    src: "RELEASE.j2"
    dest: "{{ repo_clone_path }}/{{ item.repo_name }}/{{ repo_install_chdir }}/configure/{{ item.epics_ioc_release_filename |
           default(epics_ioc_release_filename) }}"
    owner: "{{ item.make_install_as_user | default(ansible_env.USER, true) | default(ansible_user_id) }}"
    group: "{{ item.make_install_as_user | default(ansible_env.USER, true) | default(ansible_user_id) }}"
    force: true
    mode: 0644
  vars:
    __item_epics_ioc_modules: "{{ item.epics_ioc_modules | default(epics_ioc_epics_ioc_modules) }}"
    __item_epics_base_dir: "{{ item.epics_base_dir | default(epics_ioc_epics_base_dir) }}"
  become: true
  when: item.install_via_makefile is defined and
        (item.install_via_makefile | bool) and
        git_result.changed and
        (item.epics_ioc_overwrite_release_file |
            default(epics_ioc_overwrite_release_file) |
            bool)

- name: "Install {{ item.repo_name }} via Makefile"
  make:
    chdir: "{{ repo_clone_path }}/{{ item.repo_name }}/{{ repo_install_chdir }}"
    target: "{{ make_target | default('install') }}"
    params: "{{ item.make_install_opts | default({}) }}"
  become: true
  become_user: "{{ item.make_install_as_user | default(ansible_env.USER, true) | default(ansible_user_id) }}"
  loop: "{{ item.make_install_targets }}"
  loop_control:
    loop_var: make_target
  when: item.install_via_makefile is defined and
        (item.install_via_makefile | bool) and
        git_result.changed

- name: "Manage user for {{ item.repo_name }}"
  user:
    name: "{{ repo_epics_ioc_user }}"
    home: "/epics/ioc/{{ item.repo_name }}"
    comment: "{{ item.repo_name }} IOC"
    uid: "{{ ((item.epics_ioc_uid is defined) and
            (item.epics_ioc_uid)) | ternary(item.epics_ioc_uid, omit) }}"
    group: "{{ epics_ioc_group_name }}"
  become: true
  when: item.epics_manage_user | default(true) | bool

- name: Ensure IOC autosave directory exists if requested
  file:
    path: "{{ repo_ioc_autosave_dir }}"
    state: directory
    owner: "{{ repo_epics_ioc_user }}"
    group: "{{ epics_ioc_group_name }}"
    mode: 0755
  become: true
  become_user: "{{ ansible_ssh_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id) }}"
  when: item.epics_manage_autosave_dir | default(false) | bool

- name: Create list of environment variables for systemd unit
  set_fact:
    repo_ioc_systemd_env_vars_list: "{{ repo_ioc_systemd_env_vars_list | default([]) +
        [systemd_env_item.key | string + '=' + systemd_env_item.value | string] }}"
  loop: "{{ repo_ioc_env_vars | dict2items }}"
  loop_control:
    loop_var: systemd_env_item

- name: Create space-separated string for systemd Wants
  set_fact:
    repo_ioc_systemd_wants: "{{ item.epics_ioc_systemd_wants | default([]) | join(' ') }}"

- name: Create space-separated string for systemd Requires
  set_fact:
    repo_ioc_systemd_requires: "{{ item.epics_ioc_systemd_requires | default([]) | join(' ') }}"

- name: Create space-separated string for systemd After
  set_fact:
    repo_ioc_systemd_after: "{{ item.epics_ioc_systemd_after | default([]) | join(' ') }}"

- name: Create space-separated string for systemd RequireMountsFor
  set_fact:
    repo_ioc_systemd_requires_mounts_for: "{{ item.epics_ioc_systemd_requires_mounts_for | default([]) | join(' ') }}"

- name: Set base systemd unit variable
  set_fact:
    __systemd_unit_config:
      - name: "softioc-{{ item.repo_name }}"
        state: "{{ item.epics_ioc_systemd_state | default(epics_ioc_systemd_state) }}"
        enabled: "{{ item.epics_ioc_systemd_enabled | default(epics_ioc_systemd_enabled) }}"
        Unit:
          Description: "EPICS Soft IOC {{ item.repo_name }}"
          Wants: "{{ repo_ioc_systemd_wants }}"
          Requires: "{{ repo_ioc_systemd_requires }}"
          After: "{{ repo_ioc_systemd_after }}"
          RequiresMountsFor: "{{ repo_ioc_systemd_requires_mounts_for }}"
        Service:
          Environment: "{{ repo_ioc_systemd_env_vars_list }}"
          ExecStart: >-
              /usr/bin/procServ --foreground --quiet
              --chdir={{ repo_ioc_boot_dir }}
              --ignore=^C^D^]
              --coresize={{ repo_ioc_coresize }} --restrict
              --logfile={{ repo_ioc_procserv_log_file }}
              --name {{ item.repo_name }}
              {{ repo_ioc_systemd_procserv_console_port }}
              {{ repo_ioc_systemd_procserv_unix_domain_socket }}
              --timefmt={{ repo_ioc_procserv_timefmt | regex_replace('%', '%%')  }}
              {{ repo_ioc_procserv_start_script }}
          Restart: always
          User: "{{ repo_epics_ioc_user }}"
        Install:
          WantedBy: multi-user.target

- name: Set systemd notify variable if requested
  set_fact:
    __systemd_unit_config_notify: "{{ __systemd_unit_config_notify | default([]) + [
        systemd_unit_config_item | combine({
            'Service' : {
                'Type': 'notify',
                'NotifyAccess': 'all',
            }
        }, recursive=true)
    ] }}"
  when: repo_ioc_systemd_notify | bool
  loop: "{{ __systemd_unit_config }}"
  loop_control:
    loop_var: systemd_unit_config_item

- name: Set systemd UNIX domain socket runtime directory if requested
  set_fact:
    systemd_unit_config: "{{ systemd_unit_config | default([]) + [
        systemd_unit_config_notify_item | combine({
            'Service' : {
                'RuntimeDirectory': repo_ioc_unix_domain_socket | dirname
            }
        }, recursive=true)
    ] }}"
  when: repo_ioc_enable_unix_domain_socket | bool
  loop: "{{ __systemd_unit_config_notify }}"
  loop_control:
    loop_var: systemd_unit_config_notify_item

- name: "Setup {{ item.repo_name }} service file"
  include_role:
    name: lerwys.systemd
  vars:
    unit_config: "{{ systemd_unit_config }}"
