---
- name: Resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      ignore_errors: true
      paths:
        - '{{ role_path }}/vars'

- name: Define Clone/Install packages
  set_fact:
    epics_ioc_packages: "{{ __epics_ioc_packages | default ([]) }}"
  when: epics_ioc_packages is not defined

# Include Tasks

- name: Setup common environment
  include_tasks: setup-common.yml

- name: Setup RedHat environment
  include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Setup Debian environment
  include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Clone and install repositories
  include_tasks: clone-install-repo.yml
  with_items:
    - "{{ epics_ioc_repos }}"
  when:
    - epics_ioc_repos is defined

- name: Setup caRepeater service
  include: setup-caRepeater.yml
