---
- name: Ensure Clone/Install packages are installed
  package:
    name: "{{ epics_ioc_packages }}"
    state: present
  become: true
  register: package_get_result
  until: package_get_result is success
  retries: 5
  delay: 2
