---
- name: Set caRepeater service name
  set_fact:
    __carepeater_systemd_service_name: "caRepeater"
# Copied from https://github.com/epicsdeb/epics-base/blob/upstream/3.15.6/src/ca/client/caRepeater.service@
#
# [Unit]
# Description=EPICS CA Repeater
# Requires=network.target
# After=network.target
#
# [Service]
# ExecStart=@INSTALL_BIN@/caRepeater
# Restart=always
# User=daemon
#
# [Install]
# WantedBy=multi-user.target
#
- name: Setup caRepeater service file
  include_role:
    name: 0x0i.systemd
  vars:
    unit_config:
      - name: "{{ __carepeater_systemd_service_name }}"
        path: "{{ epics_ioc_carepeater_systemd_path }}"
        enabled: "{{ epics_ioc_carepeater_systemd_enabled | bool }}"
        state: "{{ epics_ioc_carepeater_systemd_state }}"
        Unit:
          Description: EPICS CA Repeater
          Requires: network.target
          After: network.target
        Service:
          ExecStart: "{{ epics_ioc_carepeater_systemd_executable }}"
          Restart: always
          User: daemon
        Install:
          WantedBy: multi-user.target
