---
- name: Converge
  hosts: all

  vars:
    epics_ioc_epics_modules_cfg:
      - |
        ASYN=/usr/lib/epics
      - |
        STREAM=/usr/lib/epics
      - |
        CALC=/usr/lib/epics

    epics_ioc_repos:
      - name: tekScope EPICS IOC
        org_url: https://github.com/brunoseivam
        repo_name: tekScope
        repo_version: master
        clone_path: /tmp
        install_via_makefile: true
        make_install_target: distclean all
        force_version: true

  roles:
    - role: ansible-role-epics-ioc
