---
- name: Converge
  hosts: all

  vars:
    epics_packages_extra:
      - epics-asyn-dev
      - epics-stream-dev
      - epics-calc-dev

    epics_ioc_repos:
      - name: tekScope EPICS IOC
        org_url: https://github.com/brunoseivam
        repo_name: tekScope
        repo_version: master
        repo_stash: true
        clone_path: /tmp
        clone_only: true
        install_via_makefile: true
        epics_ioc_modules:
          - ASYN=/usr/lib/epics
          - STREAM=/usr/lib/epics
          - CALC=/usr/lib/epics
        epics_ioc_overwrite_release_file: true
        epics_ioc_release_filename: RELEASE
        epics_base_dir: /usr/lib/epics
        epics_ioc_boot_dir: ""
        epics_manage_user: true
        epics_manage_autosave_dir: true
        epics_ioc_user_name: ioc
        epics_ioc_uid:
        epics_ioc_systemd_state: started
        epics_ioc_systemd_enabled: true
        epics_ioc_systemd_requires:
          - network.target
        epics_ioc_systemd_wants:
          - network.target
        epics_ioc_systemd_after:
          - network.target
        epics_ioc_systemd_requires_mounts_for: []
        epics_ioc_systemd_coresize:
        epics_ioc_systemd_enable_console_port: true
        epics_ioc_systemd_console_port:
        epics_ioc_systemd_enable_unix_domain_socket:
        epics_ioc_systemd_unix_domain_socket:
        epics_ioc_systemd_procserv_timefmt:
        epics_ioc_systemd_procserv_start_script: "st.cmd"
        epics_ioc_systemd_notify: false
        epics_ioc_env: {}
        epics_ioc_env_epics_ca_addr_list: "127.0.0.1"
        epics_ioc_env_epics_ca_auto_addr_list: true
        epics_ioc_env_epics_ca_max_array_bytes: 10000000
        epics_ioc_env_epics_ioc_log_port: 7004
        epics_ioc_env_epics_ca_sec_file: ""
        epics_ioc_env_epics_ioc_log_inet: ""
        epics_ioc_autosave_base_dir: /var/lib
        epics_ioc_logrotate_rotate:
        epics_ioc_logrotate_size:
        epics_ioc_logrotate_compress:
        make_install_targets:
          - distclean
          - all
        force_version: true

  roles:
    - role: ansible-role-epics-ioc
