---
- name: Converge
  hosts: all

  vars:
    epics_packages_extra:
      - epics-asyn-dev
      - epics-stream-dev
      - epics-calc-dev

    epics_ioc_repos:
      - name: tekScope EPICS IOC
        org_url: https://github.com/brunoseivam
        repo_name: tekScope
        repo_version: master
        repo_stash: true
        clone_path: /tmp
        epics_ioc_modules:
          - ASYN=/usr/lib/epics
          - STREAM=/usr/lib/epics
          - CALC=/usr/lib/epics
        epics_ioc_overwrite_release_file: true
        epics_ioc_release_filename: RELEASE
        install_via_makefile: true
        make_install_targets:
          - distclean
          - all
        force_version: true

  roles:
    - role: ansible-role-epics-ioc
