---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  flake8
provisioner:
  name: ansible
  log: ${MOLECULE_LOG_VERBOSE:-false}
  inventory:
    group_vars:
      default_group:
verifier:
  name: testinfra
  options:
    verbose: true
driver:
  name: docker
platforms:
  - name: ansible-role-epics-ioc-instance
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-debian9-ansible}"
    command: ${MOLECULE_DOCKER_COMMAND:-'/lib/systemd/systemd'}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - default_group
    dns_servers: ["${DNS_SERVER1}", "${DNS_SERVER2}"]
